Extract config-loading to config_load()
Signed-off-by: Steve Almond <steve@SilkAndSlug.com>

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -238,6 +238,51 @@ function log_verbose()	{ log_by_level "$VERBOSITY_VERBOSE" "$1";	return $?; }
 function log_debug()	{ log_by_level "$VERBOSITY_DEBUG" "$1"; 	return $?; }
 
 
+## output supported commands
+function echo_usage {
+	echo_quiet "Usage: $(basename "$0") [<options>] <command>";
+	echo_out;
+	echo_out "Where <options> is zero or more of:";
+	echo_out "   -q            Quiet. Decreases the script's verbosity";
+	echo_out "   -v            Verbose. Increases the script's verbosity. May be repeated. Max is three";
+	echo_out;
+	echo_out "Where <command> is one of:";
+	echo_out "   start \t\t Starts the server";
+	echo_out "   stop \t\t Stops the server";
+	echo_out "   kill \t\t Kills the server";
+	echo_out "   restart \t\t Restarts the server";
+	echo_out "   watchdog \t Ensures server is still running";
+	echo_out "   reload \t\t Reloads the server configuration";
+	echo_out "   backup \t\t Backups the worlds defined in the script";
+	echo_out "   whole-backup \t Backups the entire server folder";
+	echo_out "   check-update \t Checks for updates of $CB_JAR and $MC_JAR";
+	echo_out "   update \t\t Fetches the latest version of minecraft.jar server and Bukkit";
+	echo_out "   log-roll \t\t Moves and compresses the logfiles";
+	echo_out "   log \t\t\t Prints the server log";
+	echo_out "   to-disk \t\t Copies the worlds from the ramdisk to worldstorage";
+	echo_out "   save-off \t\t Flushes the world to disk and then disables saving";
+	echo_out "   save-on \t\t Re-enables saving if it was previously disabled by save-off";
+	echo_out "   say \t\t\t Prints the given string to the ingame chat";
+	echo_out "   connected \t\t Lists connected users";
+	echo_out "   playercount \t\t Prints the number of connected users";
+	echo_out "   status \t\t Displays server status";
+	echo_out "   version \t\t Displays Bukkit version and then exits";
+	echo_out "   links \t\t Creates nessesary symlinks";
+	echo_out "   last \t\t Displays recently connected users";
+	echo_out "   worlds \t\t Displays a list of available worlds";
+	echo_out "   ramdisk WORLD \t Toggles ramdisk configuration for WORLD";
+	echo_out "   overviewer WORLD \t Creates a map of the WORLD with Minecraft-Overviewer";
+	echo_out "   whitelist \t\t Prints the current whitelist";
+	echo_out "   whitelist-add NAME \t Adds the specified player to the server whitelist";
+	echo_out "   whitelist-reload \t Reloads the whitelist";
+	echo_out "   screen \t\t Shows the server screen";
+	echo_out "   script-version        Show this script's version";
+	echo_out "   help \t\t Shows this text";
+
+	return 0;
+}
+
+
 
 ########
 # Extract commandline parameters from call
@@ -293,47 +338,44 @@ function handle_commandline_options {
 }
 
 
+## load all config files, and test
+function config_load() {
+	## load local config
+	config_load_local || {
+		echo_err "Can't load local config ($CONFIG_FILE); crashing";
+		exit 1;
+	}
 
-## output supported commands
-function echo_usage {
-	echo_quiet "Usage: $(basename "$0") [<options>] <command>";
-	echo_out;
-	echo_out "Where <options> is zero or more of:";
-	echo_out "   -q            Quiet. Decreases the script's verbosity";
-	echo_out "   -v            Verbose. Increases the script's verbosity. May be repeated. Max is three";
-	echo_out;
-	echo_out "Where <command> is one of:";
-	echo_out "   start \t\t Starts the server";
-	echo_out "   stop \t\t Stops the server";
-	echo_out "   kill \t\t Kills the server";
-	echo_out "   restart \t\t Restarts the server";
-	echo_out "   watchdog \t Ensures server is still running";
-	echo_out "   reload \t\t Reloads the server configuration";
-	echo_out "   backup \t\t Backups the worlds defined in the script";
-	echo_out "   whole-backup \t Backups the entire server folder";
-	echo_out "   check-update \t Checks for updates of $CB_JAR and $MC_JAR";
-	echo_out "   update \t\t Fetches the latest version of minecraft.jar server and Bukkit";
-	echo_out "   log-roll \t\t Moves and compresses the logfiles";
-	echo_out "   log \t\t\t Prints the server log";
-	echo_out "   to-disk \t\t Copies the worlds from the ramdisk to worldstorage";
-	echo_out "   save-off \t\t Flushes the world to disk and then disables saving";
-	echo_out "   save-on \t\t Re-enables saving if it was previously disabled by save-off";
-	echo_out "   say \t\t\t Prints the given string to the ingame chat";
-	echo_out "   connected \t\t Lists connected users";
-	echo_out "   playercount \t\t Prints the number of connected users";
-	echo_out "   status \t\t Displays server status";
-	echo_out "   version \t\t Displays Bukkit version and then exits";
-	echo_out "   links \t\t Creates nessesary symlinks";
-	echo_out "   last \t\t Displays recently connected users";
-	echo_out "   worlds \t\t Displays a list of available worlds";
-	echo_out "   ramdisk WORLD \t Toggles ramdisk configuration for WORLD";
-	echo_out "   overviewer WORLD \t Creates a map of the WORLD with Minecraft-Overviewer";
-	echo_out "   whitelist \t\t Prints the current whitelist";
-	echo_out "   whitelist-add NAME \t Adds the specified player to the server whitelist";
-	echo_out "   whitelist-reload \t Reloads the whitelist";
-	echo_out "   screen \t\t Shows the server screen";
-	echo_out "   script-version        Show this script's version";
-	echo_out "   help \t\t Shows this text";
+
+	## test config is loaded
+	if [ -z "$SERVICE" ]; then
+		logger -t minecraft-init "Can't load local config ($CONFIG_FILE); crashing";
+		exit 1;
+	fi
+
+
+	## set dependant vars
+	INVOCATION="java -Xmx$MAXMEM -Xms$INITMEM -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE nogui";
+
+
+	return 0;
+}
+
+
+## load ./config
+function config_load_local() {
+	local dir="$(dirname "$(readlink -e "$0")")";
+	local file="$dir/config";
+
+	if [ ! -f "$file" ]; then
+		echo "Couldn't find config file. Please edit config.example and rename it to $file; skipping";
+		return 0;
+	fi
+
+	source "$file" || {
+		echo_err "Couldn't load config file. Please edit config.example and rename it to $file; crashing";
+		exit 1;
+	}
 
 	return 0;
 }
@@ -1648,26 +1690,11 @@ function route_command() {
 ###############################################################################
 
 
-# Loads config file
-if [ -L $0 ]
-then
-	source `readlink -e $0 | sed "s:[^/]*$:config:"`
-else
-	source `echo $0 | sed "s:[^/]*$:config:"`
-fi
-
-if [ "$SERVICE" == "" ]
-then
-	echo_err "Couldn't load config file, please edit config.example and rename it to config"
-	logger -t minecraft-init "Couldn't load config file, please edit config.example and rename it to config"
-	exit
-fi
-
-
 trap force_exit SIGINT
 
 
 handle_commandline_options "$@" || exit 1;
+config_load || exit 1;
 route_command "$@" || exit 1;	# need to inject $@ so route_command() can pass it on
 
 
